fb-add 4 subcommands-2
gen-classroom/projet-janssens_marques_lange_villagrasa pull request #16
Opened 2021-03-11 11:33 UTC by yanik23

closes #2

2021-03-11 11:37 UTC, fabio10000 requested changes
implement commands

2021-03-11 11:43 UTC, yanik23 commented
working on it

2021-03-12 10:07 UTC, yanik23 commented
Added the implementation of the subcommands. Please tell me if something is wrong.
Best regards !

Yanik

2021-03-12 10:25 UTC, yanik23 commented
Added the main that wasn't in the previous commits.

2021-03-18 15:58 UTC, fabio10000 commented on my-app/src/main/java/com/gen/app/Init.java
> +import org.w3c.dom.ls.LSOutput;
unused import must be removed

2021-03-18 16:00 UTC, fabio10000 requested changes
There's an unused import that must be removed, for more details please have a look at my comment

2021-03-18 16:31 UTC, yanik23 commented
Removed the unused import, let me know if anything is still missing. Best regards.

2021-03-18 16:33 UTC, fabio10000 approved these changes

2021-03-18 16:33 UTC, merged